#
### project ##########################################################################
# updated: 2023-11-11
#


### mypy ############################################################################

[tool.mypy]
  # exclude = "tests"
  files = ["custom_components"]
  follow_imports = "skip"  # TODO: don't use this feature


[[tool.mypy.overrides]]
  module = ["homeassistant.*", "ramses_rf.*", "ramses_tx.*"]

  ignore_missing_imports = true



#
## ruff ##############################################################################

[tool.ruff]
  # exclude = ["tests/deprecated/*.py"]
  src = ["custom_components"]
  target-version = "py311"  # Assume Python 3.11


[tool.ruff.lint]
  select = [
    "B",  # flake8-bugbear
    "E",  # pycodestyle
    "F",  # Pyflakes
    "I",  # isort
    # "SIM",  # flake8-simplify
    "UP",  # pyupgrade
  ]
  ignore = ["E501"]
  # E501  - Line too long

[tool.ruff.flake8-import-conventions.extend-aliases]
  voluptuous = "vol"
  "homeassistant.helpers.area_registry" = "ar"
  "homeassistant.helpers.config_validation" = "cv"
  "homeassistant.helpers.device_registry" = "dr"
  "homeassistant.helpers.entity_registry" = "er"
  "homeassistant.helpers.issue_registry" = "ir"
  "homeassistant.util.dt" = "dt_util"

[tool.ruff.flake8-pytest-style]
  fixture-parentheses = false

[tool.ruff.flake8-tidy-imports.banned-api]
  "async_timeout".msg = "use asyncio.timeout instead"
  "pytz".msg = "use zoneinfo instead"

[tool.ruff.isort]
  force-sort-within-sections = true
  known-first-party = ["homeassistant"]
  combine-as-imports = true
  split-on-trailing-comma = false

[tool.ruff.mccabe]
  max-complexity = 25
