# Evohome CC services.yaml entries

set_zone_override:
  description: This service call will set the setpoint of a zone, as identified by its entity_id, for a specified period of time (TemporaryOverride). However, if no period of time is provided (c.f. a duration of 0, below), then the change is permanent (PermanentOverride). The duration can be up to 24 hours, after which the zone mode will revert to schedule (FollowSchedule). If the duration is 0 hours, then the change will be until the next setpoint.
  fields:
    entity_id:
    setpoint:
    duration:

clear_zone_override:
  description: This service call is used to set a zone, as identified by its entity_id, to FollowSchedule.
  fields:
    entity_id:

set_system_mode:
  description: This service call will set the operating mode of the system for a specified period of time, after which it will revert to Auto. However, if no period of time is provided, then the change is permanent.
  fields:
    mode:
    duration:
      description: For AutoWithEco, the period of time is a duration is up to 24 hours. For the other modes, such as Away, the duration is a period of days, where 1 day will revert at midnight tonight, and 2 days reverts at midnight tomorrow.

reset_system:
  description: This service call will set the operating mode of the system to AutoWithReset, and reset all the zones to FollowSchedule.